<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>DevKit.TaskMgmt.Contracts</Title>
    <RootNamespace>Integration.DevKit.TaskMgmt.Contracts</RootNamespace>
    <Version>1.0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Integration.DevKit.Core\Integration.DevKit.Core.csproj" />
  </ItemGroup>

</Project>
