<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>DevKit.ProcessLauncher</Title>
    <RootNamespace>Integration.DevKit.ProcessLauncher</RootNamespace>
    <Version>1.0.0.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Integration.DevKit.ProcessLauncher.Contracts\Integration.DevKit.ProcessLauncher.Contracts.csproj" />
  </ItemGroup>

</Project>
