<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>DevKit.ThreadLocks</Title>
    <RootNamespace>Integration.DevKit.ThreadLocks</RootNamespace>
    <Version>1.2.0.0-preview</Version>
    <PackageId>Integration.DevKit.ThreadLocks</PackageId>
    <PackageProjectUrl>https://www.nuget.org/packages/Integration.DevKit.ThreadLocks</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Integration.DevKit.Core\Integration.DevKit.Core.csproj" />
  </ItemGroup>

</Project>
