<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>DevKit.TaskMgmt</Title>
    <RootNamespace>Integration.DevKit.TaskMgmt</RootNamespace>
    <Version>1.0.1.3</Version>
    <PackageId>Integration.DevKit.TaskMgmt</PackageId>
    <PackageProjectUrl>https://www.nuget.org/packages/Integration.DevKit.TaskMgmt</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Integration.DevKit.TaskMgmt.Contracts\Integration.DevKit.TaskMgmt.Contracts.csproj" />
  </ItemGroup>

</Project>
