<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AndrewM5.DevKit.Core\AndrewM5.DevKit.Core.csproj" />
    <ProjectReference Include="..\AndrewM5.DevKit.Logging.Abstractions\AndrewM5.DevKit.Logging.Abstractions.csproj" />
  </ItemGroup>

</Project>
