<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>DevKit.Core</Title>
    <RootNamespace>Integration.DevKit.Core</RootNamespace>
    <Version>1.0.1.5</Version>
    <PackageId>Integration.DevKit.Core</PackageId>
    <PackageProjectUrl>https://www.nuget.org/packages/Integration.DevKit.Core</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Integration.DevKit.CustomLogger.Contracts\Integration.DevKit.CustomLogger.Contracts.csproj" />
  
  </ItemGroup>
</Project>
