<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>DevKit.ThreadSafeItems</Title>
    <RootNamespace>Integration.DevKit.ThreadSafeItems</RootNamespace>
    <Version>1.0.1.1</Version>
    <PackageId>Integration.DevKit.ThreadSafeItems</PackageId>
    <PackageProjectUrl>https://www.nuget.org/packages/Integration.DevKit.ThreadSafeItems</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Integration.DevKit.ThreadLocks\Integration.DevKit.ThreadLocks.csproj" />
  </ItemGroup>

</Project>
